version: '3'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017

  migration:
    build: mongo-migration
    environment:
      - DATABASE_HOST=mongo
    depends_on:
      - mongo

  content-admin:
    build: content-admin
    environment:
      - DATABASE_HOST=mongo
    depends_on:
      - mongo
    ports:
      - 1337:1337
    command: yarn develop
    volumes:
      - ./content-admin/api:/opt/app/api
      - ./content-admin/config:/opt/app/config
      - ./content-admin/extensions:/opt/app/extensions
      - ./content-admin/public:/opt/app/public
    restart: always

  front-end:
    build: front-end
    depends_on:
      - content-admin
    ports:
      - 8080:8080
    command: sh -c "yarn install && yarn develop"
    volumes:
      - ./front-end/src:/opt/app/src
